# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=anis
spring.datasource.password=anis1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Hibernate — none means Flyway owns schema, Hibernate just uses it
spring.jpa.hibernate.ddl-auto=none

# JWT
app.jwt.secret=3f8b2c1d9e4a7f6b0c5d2e1a8f3b9c4d7e2a1f6b0c5d3e8a7f2b1c4d9e6a3f8b
app.jwt.expiration-ms=900000
app.jwt.refresh-expiration-ms=604800000

# Logging
logging.level.root=INFO
logging.level.com.taskmanager=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Super admin seed
app.super-admin.email=superadmin@taskmanager.com
app.super-admin.password=SuperAdmin@123

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=false
logging.level.org.flywaydb=DEBUG